_beatspot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users.views import FollowedList, FollowersList, ProfileDetailView

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path("admin/admin", admin.site.urls),
    path("users/", include("users.urls")),
    path("<slug:slug>", ProfileDetailView.as_view(), name="user_profile"),
    path("<slug:slug>/followers", FollowersList.as_view(), name="followers"),
    path("<slug:slug>/followed", FollowedList.as_view(), name="followed"),
    path("posts/", include("posts.urls")),
    path("beats/", include("beats.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

beats/urls.py
from django.urls import path

from beats.views import BeatDetailView, like_beat, AllBeatsList

app_name = "beats"

urlpatterns = [
    path("likes/", like_beat, name="like_beat"),

    path('all/', AllBeatsList.as_view(), name='all_beats_list'), #todo: change this url to waiting-room for beats
    path("<int:pk>/<slug:slug>", BeatDetailView.as_view(), name="beat_detail"),
]

beats/models.py
from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
from embed_video.fields import EmbedVideoField

from users.models import Profile


class Base(models.Model):
    created_on = models.DateTimeField(_("created"), auto_now_add=True, null=True)
    edit_date = models.DateTimeField(_("edited"), auto_now=True)

    class Meta:
        abstract = True


class BeatCategory(Base):
    category_name = models.CharField(_("category name"), max_length=128)
    slug = models.SlugField(null=False, unique=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category_name)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("Beat category")
        verbose_name_plural = _("Beat categories")
        ordering = ("id",)

    def __str__(self):
        return self.category_name


class Beat(Base):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="beat_author", verbose_name=_("Author")
    )

    beat_title = models.CharField(_("beat title"), max_length=120)
    beat_link = EmbedVideoField(_("beat link"), blank=False, null=False)
    beat_category = models.ForeignKey(
        BeatCategory, on_delete=models.CASCADE, related_name="categories", verbose_name=_("beat category")
    )
    slug = models.SlugField(null=False, unique=False)
    is_promoted = models.BooleanField(_("Id promoted"), default=False)
    price = models.SmallIntegerField(_("Price"), null=True, blank=True)
    likes = models.ManyToManyField(
        Profile, related_name="likes", through="BeatLike", blank=True, default=None, verbose_name=_("Likes")
    )
    #todo: add short beat description field

    @property
    def num_likes(self):
        return self.likes.all().count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.beat_title)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("Beat")
        verbose_name_plural = _("Beats")
        ordering = ("id",)

    def __str__(self):
        return self.beat_title


class BeatLike(Base):
    like_from = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="like_from", verbose_name=_("Like from")
    )
    like_to = models.ForeignKey(Beat, on_delete=models.CASCADE, related_name="like_to", verbose_name=_("Like to"))

    class Meta:
        db_table = "beats_beatlike"
        constraints = [models.UniqueConstraint(fields=["like_from", "like_to"], name="unique_likes")]
        ordering = ("-created_on",)

    def __str__(self):
        return f"{self.like_from} lubi {self.like_to}"

beats/views.py
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView

from beats.models import Beat, BeatLike


def like_beat(request):
    user = request.user
    if request.method == "POST":
        beat_id = request.POST.get("beat_id")
        beat_obj = Beat.objects.get(id=beat_id)
        if user not in beat_obj.likes.all():
            BeatLike.objects.get_or_create(like_from=user, like_to=beat_obj)
        else:
            BeatLike.objects.filter(like_from=user, like_to=beat_obj).delete()
    return JsonResponse({"status": "ok", "likes_number": beat_obj.likes.count()})


class BeatDetailView(DetailView):
    model = Beat
    template_name = "beats/beat_detail.html"

    def get_success_url(self):
        pk = self.kwargs["pk"]
        slug = self.kwargs["slug"]
        return reverse_lazy("beats:beat_detail", kwargs={"pk": pk, "slug": slug})


# todo: this will be waiting room for beats like 'wykopalisko'
class AllBeatsList(ListView):
    """All Beats List - all beats added by users. From newest to oldest."""
    model = Beat
    template_name = 'beats/all_beats_list.html'
    context_object_name = 'all_beats'
    paginate_by = 2

    def get_queryset(self):
        return self.model.objects.all().order_by('-pk')

beats/templates/beats/all_beats_list.html
{% extends 'web/base.html' %}
{% load static %}
{% load embed_video_tags %}

{% block title %}ALL BEATS{% endblock %}

{% block body %}
    {% if object_list %}

        <div class="infinite-container">
            <div class="infinite-item">

                {% for beats in all_beats %}
                    {{ beats.beat_title }} <br>
                    {% video beats.beat_link 'small' %}

                    <div class="total-likes">
                        {% with total_likes=beats.likes.count %}
                            Polubień ({{ total_likes }})<br>
                        {% endwith %}
                    </div>

                    <form action="{% url 'beats:like_beat' %}" method="POST" class="like-form">
                        {% csrf_token %}
                        <input type="hidden" name="beat_id" value="{{ beats.id }}" class="like_id">
                        <button type="submit" class="like-btn{{ beats.id }} like-btn">
                            {% if request.user not in beats.likes.all %}
                                Like
                            {% else %}
                                UnLike
                            {% endif %}
                        </button>
                    </form>
                    <br><br>

                {% endfor %}
            </div>
        </div>
        <div class="loading">
            <div class="d-flex justify-content-center">
                <div class="spinner-border" role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
        {% if page_obj.has_next %}
            <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
    {% endif %}
{% endblock %}


{% block scripts %}
    <script src="{% static "js/jquery.waypoints.min.js" %}"></script>
    <script src="{% static "js/infinite.min.js" %}"></script>
    <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            offset: 'bottom-in-view',
            onBeforePageLoad() {
                $('.loading').show();
                $('.infinite-more-link').hide();
            },
            onAfterPageLoad: function () {
                $(`.loading`).hide();
            }
        });


    </script>
{% endblock %}

beats/templates/beats/beat_detail.html
{% extends 'web/base.html' %}
{% load static %}

{% block title %} BEAT: {{ beat.beat_title }} {% endblock %}

{% block body %}

    {{ beat.beat_title }}<br>

    <div class="total-likes">
        {% with total_likes=beat.likes.count %}
            Polubień ({{ total_likes }})<br>
        {% endwith %}
    </div>


    <form action="{% url 'beats:like_beat' %}" method="POST" class="like-form">
        {% csrf_token %}
        <input type="hidden" name="beat_id" value="{{ beat.id }}" class="like_id">
        <button type="submit" class="like-btn{{ beat.id }} like-btn">
            {% if request.user not in beat.likes.all %}
                Like
            {% else %}
                UnLike
            {% endif %}
        </button>
    </form>

{% endblock %}


{% block scripts %}
    <script>
        $(document).ready(function () {
            $('.like-form').submit(function (e) {
                e.preventDefault();
                const csrf = $('input[name ="csrfmiddlewaretoken"]').val()
                const beat_id = $('.like_id').val();
                $.post('/beats/likes/', {'beat_id': beat_id, 'csrfmiddlewaretoken': csrf}, function (data) {
                    console.log(data);
                    $('.total-likes').html(`Polubień (${data.likes_number})`)
                    if ($('.like-btn').html().trim() === 'Like') {
                        $('.like-btn').html('UnLike');
                    } else {
                        $('.like-btn').html('Like');
                    }
                });
            });
        });
    </script>
{% endblock %}