_beatspot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from users.views import FollowedList, FollowersList, ProfileDetailView

urlpatterns = [
    path('tinymce/', include('tinymce.urls')),
    path("admin/admin", admin.site.urls),
    path("users/", include("users.urls")),
    path("<slug:slug>", ProfileDetailView.as_view(), name="user_profile"),
    path("<slug:slug>/followers", FollowersList.as_view(), name="followers"),
    path("<slug:slug>/followed", FollowedList.as_view(), name="followed"),
    path("posts/", include("posts.urls")),
    path("beats/", include("beats.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

beats/urls.py
from django.urls import path

from beats.views import BeatDetailView, like_beat, AllBeatsList

app_name = "beats"

urlpatterns = [
    path("likes/", like_beat, name="like_beat"),

    path('all/', AllBeatsList.as_view(), name='all_beats_list'), #todo: change this url to waiting-room for beats
    path("<int:pk>/<slug:slug>", BeatDetailView.as_view(), name="beat_detail"),
]

users/urls.py
from django.urls import path

from users.views import follow_user

app_name = "users"

urlpatterns = [
    path("followers/", follow_user, name="follow_user"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import gettext_lazy as _
from hitcount.models import HitCountMixin
from hitcount.settings import MODEL_HITCOUNT
from tinymce.models import HTMLField


class UserFollowing(models.Model):
    following_from = models.ForeignKey(
        "Profile", related_name="following_from", on_delete=models.CASCADE, verbose_name=_("Following from")
    )
    follow_to = models.ForeignKey(
        "Profile", related_name="follow_to", on_delete=models.CASCADE, verbose_name=_("Following to")
    )
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = "users_userfollowing"
        constraints = [models.UniqueConstraint(fields=["following_from", "follow_to"], name="unique_followers")]
        ordering = ("-created",)

    def __str__(self):
        return f"FROM:{self.following_from} TO:{self.follow_to}"


class Profile(AbstractUser, HitCountMixin):
    edit_date = models.DateTimeField(_("edited"), auto_now=True)
    profile_photo = models.ImageField(_("avatar"), blank=True, null=True, upload_to="profile_photos")
    short_info = models.TextField(_("short info"), max_length=350, blank=True, null=True)
    localization = models.CharField(
        _("localization"), max_length=40, null=True, blank=True
    )  # todo: change to smth cool!
    slug = models.SlugField(null=False, unique=True)
    following = models.ManyToManyField(
        "self", through=UserFollowing, related_name="followers", verbose_name=_("following"), symmetrical=False
    )
    is_regular_profile = models.BooleanField(_("Is regular users"), default=False)
    is_provider_profile = models.BooleanField(_("Is provider users"), default=False)

    @property
    def num_followers(self):
        return self.followers.all().count()

    @property
    def num_followed(self):
        return self.following.all().count()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.username)
        return super().save(*args, **kwargs)

    hit_count_generic = GenericRelation(
        MODEL_HITCOUNT, object_id_field="object_pk", related_query_name="hit_count_generic_relation"
    )

    class Meta:
        verbose_name = _("users")
        verbose_name_plural = _("profiles")
        ordering = ("id",)

    def __str__(self):
        return self.username


class ProviderCategory(models.Model):
    category_name = models.CharField(_("category name"), max_length=128)
    created_on = models.DateTimeField(_("created"), auto_now_add=True, null=True)
    edit_date = models.DateTimeField(_("edited"), auto_now=True)
    slug = models.SlugField(null=False, unique=False)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.category_name)
        return super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("Provider category")
        verbose_name_plural = _("Provider categories")
        ordering = ("id",)

    def __str__(self):
        return self.category_name


class ProviderProfile(models.Model):
    id = models.AutoField(primary_key=True)
    user_profile = models.OneToOneField(Profile, on_delete=models.SET_NULL, null=True, verbose_name=_("user users"))
    provider_category = models.ForeignKey(
        ProviderCategory, on_delete=models.CASCADE, related_name="categories", verbose_name=_("provider category")
    )
    created_at = models.DateTimeField(_("created"), auto_now_add=True)
    edit_date = models.DateTimeField(_("editeded"), auto_now=True)
    is_promoted = models.BooleanField(_("is promoted"), default=False)
    background_image = models.ImageField(_("background image"), blank=True, null=True, upload_to="background_image")
    facebook_url = models.URLField(max_length=500, blank=True, null=True)
    soundcloud_url = models.URLField(max_length=500, blank=True, null=True)
    youtube_url = models.URLField(max_length=500, blank=True, null=True)
    instagram_url = models.URLField(max_length=500, blank=True, null=True)
    website_url = models.URLField(max_length=500, blank=True, null=True)
    long_info = HTMLField(max_length=1500, null=False, blank=True)

    is_verify = models.BooleanField(_("Is verify"), default=False)

    # todo: add long description - html field?
    # long_description = HTMLField(_("long description"), max_length=3000, blank=True, null=True)

    class Meta:
        verbose_name = _("Provider users")
        verbose_name_plural = _("Provider profiles")
        ordering = ("id",)

    def __str__(self):
        return self.user_profile.username

users/views.py
from django.http import JsonResponse
from django.views.generic import ListView
from hitcount.views import HitCountDetailView

from users.models import Profile, UserFollowing

class ProfileDetailView(HitCountDetailView):
    model = Profile
    template_name = "users/profile.html"
    count_hit = True


def follow_user(request):
    user = request.user
    if request.method == "POST":
        user_id = request.POST.get("user_id")
        user_obj = Profile.objects.get(id=user_id)

        if user not in user_obj.followers.all():
            UserFollowing.objects.get_or_create(following_from=user, follow_to=user_obj)
        else:
            UserFollowing.objects.filter(following_from=user, follow_to=user_obj).delete()
    return JsonResponse({"status": "ok", "followers_number": user_obj.followers.count()})


class FollowersList(ListView):
    """All users who follow User"""
    template_name = "users/followers_list.html"
    model = Profile

    def get_queryset(self):
        queryset = Profile.objects.get(slug=self.kwargs["slug"]).follow_to.all()
        return queryset


class FollowedList(ListView):
    """All users who User follow"""
    template_name = "users/followed_list.html"
    model = Profile

    def get_queryset(self):
        queryset = Profile.objects.get(slug=self.kwargs["slug"]).following_from.all()
        return queryset

users/templates/users/followed_list.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}
    Wszyscy użytkownicy których obserwuje [NAZWA UŻYTKOWNIKA]<br><br>

    {% for followed in object_list %}
        <a href="{% url 'user_profile' followed.follow_to.slug %}">{{ followed.follow_to.username }} </a><br>

        {{ followed.follow_to.username }} id: {{ followed.follow_to.id }} <br>
        Liczba followersów {{ followed.follow_to.username }}:
        {% with total_followers=followed.follow_to.followers.count %}
            ({{ total_followers }} Followers)
        {% endwith %} <br>

        Mój ID: {{ request.user.id }} <br><br>

    {% endfor %}
{% endblock %}

users/templates/users/followers_list.html
{% extends 'web/base.html' %}
{% load static %}

{% block body %}

    Wszyscy obserwujący użytkownika [NAZWA UŻYTKOWNIKA]  <br>

    {% for follow in object_list %}
        <a href="{% url 'user_profile' follow.following_from.slug %}">{{ follow.following_from.username }} </a><br>

    {% endfor %}
{% endblock %}

users/templates/users/profile.html
{% extends 'web/base.html' %}
{% load static %}

{% block title %} PROFILE {{ profile.username }} {% endblock %}

{% block body %}

    Profile <br>

    Username:
    {{ profile.username }}
    <br>

    {% if  request.user.username != profile.username %}
        <form action="{% url 'users:follow_user' %}" method="POST" class="follow-form" id="{{ profile.id }}">
            {% csrf_token %}
            <input type="hidden" name="user_id" value="{{ profile.id }}" class="follow_id">
            <button type="submit" class="follow-btn{{ profile.id }} follow-btn">
                {% if request.user not in profile.followers.all %}
                    Follow
                {% else %}
                    Unfollow
                {% endif %}
            </button>
        </form>
    {% endif %}

    <a href="{% url 'followers' slug=profile.slug %}">
        <div class="total-followers">
            {% with total_followers=profile.followers.count %}
                Obserwujących ({{ total_followers }})<br>
            {% endwith %}
        </div>
    </a> - użytkownicy którzy obserwują tego usera<br>



    {% for follower in profile.followers.all %}
        {{ follower.username }} <br>
    {% endfor %}

    <br>

    <a href="{% url 'followed' slug=profile.slug %}"> {% with total_followers=profile.following.count %}
        Obserwuje ({{ total_followers }})
    {% endwith %} </a> <br>- użytkoniwcy śledzeni przez tego użytkownika <br>

    {% for follower in profile.following.all %}
        {{ follower.username }} <br>
    {% endfor %}
    <br><br>

    Views:
    {{ hitcount.total_hits }}
{% endblock %}

{% block scripts %}
    <script>
        $(document).ready(function () {
            $('.follow-form').submit(function (e) {
                e.preventDefault();
                const csrf = $('input[name ="csrfmiddlewaretoken"]').val()
                const user_id = $('.follow_id').val();
                $.post('/users/followers/', {'user_id': user_id, 'csrfmiddlewaretoken': csrf}, function (data) {
                    console.log(data);
                    $('.total-followers').html(`Obserwujących (${data.followers_number})`)
                    if ($('.follow-btn').html().trim() === 'Follow') {
                        $('.follow-btn').html('Unfollow');
                    } else {
                        $('.follow-btn').html('Follow');
                    }
                });
            });
        });
    </script>
{% endblock %}